# Generated by Django 3.0.7 on 2020-06-29 12:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('send_mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailihistory',
            name='date_of_send',
            field=models.DateField(default=datetime.datetime(2020, 6, 29, 12, 47, 31, 489667, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='emailihistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='Sender'),
        ),
    ]
