# Generated by Django 3.0.7 on 2020-06-29 13:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('send_mail', '0003_auto_20200629_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailihistory',
            name='date_of_send',
            field=models.DateField(default=datetime.datetime(2020, 6, 29, 13, 7, 11, 397192, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='emailihistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='Sender'),
        ),
    ]
