# Generated by Django 3.0.7 on 2020-06-29 13:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0004_auto_20200629_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailihistory',
            name='date_of_send',
            field=models.DateField(default=datetime.datetime(2020, 6, 29, 13, 8, 0, 273053, tzinfo=utc)),
        ),
    ]
