# Generated by Django 3.0.7 on 2020-06-29 14:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0005_auto_20200629_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailihistory',
            name='send_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailihistory',
            name='date_of_send',
            field=models.DateField(default=datetime.datetime(2020, 6, 29, 14, 14, 58, 608340, tzinfo=utc)),
        ),
    ]
